DOAN/Controllers/KhachHangController.cs
using DOAN.Models;
using DOAN.Utilities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace DOAN.Controllers
{
	public class KhachHangController : Controller
	{
		private readonly QlksContext _context;
		public KhachHangController(QlksContext context)
		{
			_context = context;
		}
		public IActionResult Index()
		{
            if (!Functions.IsLogin())
                return RedirectToAction("Index", "DangNhap");
            var mn = _context.TbKhachHangs.OrderBy(m=>m.IdKh).ToList();
			return View(mn);
		}
		public IActionResult Delete(string? id)
		{
			if (id == null)
			{
				return NotFound();
			}
			var mn = _context.TbKhachHangs.Find(id);
			if (mn == null)
			{
				return NotFound();
			}
			return View(mn);
		}
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(string id)
		{
            var khachHang = _context.TbKhachHangs.Find(id);
            if (khachHang == null)
            {
                return NotFound();
            }
            // Tìm tất cả các bản ghi từ bảng tbCTPhieuDangKy có IdKH tương ứng
            var phieuDangKyList = _context.TbCtphieuDangKies.Where(p => p.IdKh == id).ToList();
            if (phieuDangKyList.Any())
            {
                // Nếu có bản ghi, xóa chúng trước
                _context.TbCtphieuDangKies.RemoveRange(phieuDangKyList);
            }

            _context.TbKhachHangs.Remove(khachHang);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
        public IActionResult Create()
        {
            var mn = _context.TbKhachHangs.OrderBy(m=>m.IdKh).ToList();
            ViewBag.mn = mn;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(TbKhachHang mn)
        {
            if (ModelState.IsValid)
            {
                // Thêm dữ liệu mới vào bảng TbKhachHang trong cơ sở dữ liệu
                _context.TbKhachHangs.Add(mn);
                _context.SaveChanges(); // Lưu thay đổi vào cơ sở dữ liệu

                return RedirectToAction("Index"); // Chuyển hướng đến trang Index sau khi thêm thành công
            }

            // Nếu ModelState không hợp lệ, trả về View với model để hiển thị lỗi
            return View(mn);
        }
        public IActionResult Edit(string? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var po = _context.TbKhachHangs.Find(id);
            if (po == null)
            {
                return NotFound();
            }

            var polist = _context.TbKhachHangs.OrderBy(m => m.IdKh).ToList();
            ViewBag.poList = polist;
            return View(po);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(TbKhachHang po)
        {
            if (ModelState.IsValid)
            {
                _context.TbKhachHangs.Update(po);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(po);
        }
    }
}

DOAN/Views/KhachHang/Create.cshtml
@using DOAN.Utilities;
@model DOAN.Models.TbKhachHang;

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="page-wrapper">
    <div class="content container-fluid">
        <div class="page-header">
            <div class="row align-items-center">
                <div class="col">
                    <h3 class="page-title mt-5">Chỉnh sửa khách hàng </h3>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <form method="post">
                    <div class="row formtype">
                        <div class="col-md-4">
                            <div class="form-group">
                                <label asp-for="IdKh">ID Khách Hàng</label>
                                <input type="text" class="form-control mb-3" asp-for="IdKh" placeholder="KH">
                                <span asp-validation-for="IdKh" class="alert-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label asp-for="TenKh">Tên Khách Hàng</label>
                                <input type="text" class="form-control mb-3" asp-for="TenKh" placeholder="">
                                <span asp-validation-for="TenKh" class="alert-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label asp-for="NgaySinh">Ngày Sinh</label>
                                <div class="cal-icon">
                                    <input id="datetimepicker3" type="text" class="form-control datetimepicker" asp-for="NgaySinh" placeholder="">
                                </div>
                                <span asp-validation-for="NgaySinh" class="alert-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label asp-for="GioTinh">Giới Tính</label>
                                <input type="text" class="form-control mb-3" asp-for="GioTinh" placeholder="">
                                <span asp-validation-for="GioTinh" class="alert-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label asp-for="DienThoai">Số Điện thoại</label>
                                <input type="text" class="form-control mb-3" asp-for="DienThoai" placeholder="">
                                <span asp-validation-for="DienThoai" class="alert-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label asp-for="DiaChi">Địa Chỉ</label>
                                <input type="text" class="form-control mb-3" asp-for="DiaChi" placeholder="">
                                <span asp-validation-for="DiaChi" class="alert-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label asp-for="SoCccd">Căn cước công dân </label>
                                <input type="text" class="form-control mb-3" asp-for="SoCccd" placeholder="">
                                <span asp-validation-for="SoCccd" class="alert-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label asp-for="Email">Email</label>
                                <input type="text" class="form-control mb-3" asp-for="Email" placeholder="">
                                <span asp-validation-for="Email" class="alert-danger"></span>
                            </div>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary buttonedit">Lưu</button>
                    <a asp-controller="KhachHang" asp-action="Index" class="btn btn-lg btn-warning p-2">Quay lại</a>
                </form>
            </div>
        </div>
    </div>
</div>

<script>
    $(function () {
        $('#datetimepicker3').datetimepicker({
            format: 'LT'
        });
    });
</script>

DOAN/Views/KhachHang/Edit.cshtml
@using DOAN.Utilities;
@model DOAN.Models.TbKhachHang;

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="page-wrapper">
    <div class="content container-fluid">
        <div class="page-header">
            <div class="row align-items-center">
                <div class="col">
                    <h3 class="page-title mt-5">Chỉnh sửa khách hàng </h3>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <form asp-action="Edit" method="post">
                    <div class="row formtype">
                        <div class="col-md-4">
                            <div class="form-group">
                                <label asp-for="IdKh">ID Khách Hàng</label>
                                <input type="text" class="form-control mb-3" asp-for="IdKh" placeholder="KH">
                                <span asp-validation-for="IdKh" class="alert-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label asp-for="TenKh">Tên Khách Hàng</label>
                                <input type="text" class="form-control mb-3" asp-for="TenKh" placeholder="">
                                <span asp-validation-for="TenKh" class="alert-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label asp-for="NgaySinh">Ngày Sinh</label>
                                <div class="cal-icon">
                                    <input id="datetimepicker3" type="text" class="form-control datetimepicker" asp-for="NgaySinh" placeholder="">
                                </div>
                                <span asp-validation-for="NgaySinh" class="alert-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label asp-for="GioTinh">Giới Tính</label>
                                <input type="text" class="form-control mb-3" asp-for="GioTinh" placeholder="">
                                <span asp-validation-for="GioTinh" class="alert-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label asp-for="DienThoai">Số Điện thoại</label>
                                <input type="text" class="form-control mb-3" asp-for="DienThoai" placeholder="">
                                <span asp-validation-for="DienThoai" class="alert-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label asp-for="DiaChi">Địa Chỉ</label>
                                <input type="text" class="form-control mb-3" asp-for="DiaChi" placeholder="">
                                <span asp-validation-for="DiaChi" class="alert-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label asp-for="SoCccd">Căn cước công dân </label>
                                <input type="text" class="form-control mb-3" asp-for="SoCccd" placeholder="">
                                <span asp-validation-for="SoCccd" class="alert-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label asp-for="Email">Email</label>
                                <input type="text" class="form-control mb-3" asp-for="Email" placeholder="">
                                <span asp-validation-for="Email" class="alert-danger"></span>
                            </div>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary buttonedit">Lưu</button>
                    <a asp-controller="KhachHang" asp-action="Index" class="btn btn-lg btn-warning p-2">Quay lại</a>
                </form>
            </div>
        </div>
    </div>
</div>

<script>
    $(function () {
        $('#datetimepicker3').datetimepicker({
            format: 'LT'
        });
    });
</script>

DOAN/Views/KhachHang/Index.cshtml
@using DOAN.Models;
@model IList<TbKhachHang>

<div class="page-wrapper">
	<div class="content container-fluid">
		<div class="page-header">
			<div class="row align-items-center">
				<div class="col">
					<div class="mt-5">
						<div class="top-nav-search">
							<form>
								<input type="text" class="form-control" placeholder="Tìm Kiếm">
								<button class="btn" type="submit"><i class="fas fa-search"></i></button>
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-sm-12">
				<div class="card card-table">
					<div class="card-body booking_card">
						<div class="table-responsive">
							<table class="datatable table table-stripped table table-hover table-center mb-0">
								<thead>
									<tr>
										<th>ID Khách Hàng</th>
										<th>Họ Tên</th>
										<th>Ngày sinh</th>
										<th>Giới tính</th>
										<th>Điện thoại</th>
										<th>Số CCCD</th>
										<th>Địa chỉ</th>
										<th>Email</th>
										<th>Hành động</th>
									</tr>
								</thead>
								<tbody>
									@foreach(var kh in Model)
									{
										<tr>
											<td>@kh.IdKh</td>
											<td>@kh.TenKh</td>
											<td>@((kh.NgaySinh != null) ? ((DateTime)kh.NgaySinh).ToString("dd/MM/yyyy") : "")</td>
											<td>@kh.GioTinh</td>
											<td>@kh.DienThoai</td>
											<td>@kh.SoCccd</td>
											<td>@kh.DiaChi</td>
											<td>@kh.Email</td>
											<td class="text-right">
												<div class="dropdown dropdown-action">
													<a href="#" class="action-icon dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><i class="fas fa-ellipsis-v ellipse_color"></i></a>
													<div class="dropdown-menu dropdown-menu-right">
														<a class="dropdown-item" asp-action="Edit" asp-route-id="@kh.IdKh"><i class="fas fa-pencil-alt m-r-5"></i>Sửa</a>

														
														<a class="dropdown-item delete-action" data-toggle="modal" data-target="#deleteModal-@kh.IdKh"><i class="fas fa-trash-alt m-r-5"></i> Xóa</a>
													</div>
												</div>
											</td>
										</tr>
									}

								</tbody>
							</table>
						</div>
					</div>
				</div>
			</div>
		</div>
		@foreach(var kh in Model)
		{
			<div class="modal fade delete-modal" id="deleteModal-@kh.IdKh" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
				<div class="modal-dialog modal-dialog-centered">
					<div class="modal-content">
						<div class="modal-body text-center">
							<img src="~/assets/img/sent.png" alt="" width="50" height="46">
							<h3 class="delete_class">Bạn chắc chắn muốn xóa không?</h3>
							<div class="m-t-20">
								<a href="#" class="btn btn-white" data-dismiss="modal">Close</a>
								<form asp-action="Delete" asp-route-id="@kh.IdKh">
									<button type="submit" class="btn btn-danger">Xóa</button>
								</form>
								
							</div>
						</div>
					</div>
				</div>
			</div>
		}
	</div>
</div>