DOAN/Controllers/NhanVienController.cs
using DOAN.Models;
using DOAN.Utilities;
using Microsoft.AspNetCore.Mvc;

namespace DOAN.Controllers
{
	public class NhanVienController : Controller
	{
		private readonly QlksContext _context;
		public NhanVienController(QlksContext context)
		{
			_context = context;
		}
		public IActionResult Index()
		{
            if (!Functions.IsLogin())
                return RedirectToAction("Index", "DangNhap");
            var mn = _context.TbNhanViens.OrderBy(m => m.IdNv).ToList();
			return View(mn);
		}
		public IActionResult Delete(string? id)
		{
			if (id == null)
			{
				return NotFound();
			}
			var mn = _context.TbNhanViens.Find(id);
			if (mn == null)
			{
				return NotFound();
			}
			return View(mn);
		}
		[HttpPost, ActionName("Delete")]
		[ValidateAntiForgeryToken]
		public IActionResult DeleteConfirmed(string id)
		{
			var nv = _context.TbNhanViens.Find(id);
			if (nv == null)
			{
				return NotFound();
			}
			// Tìm tất cả các bản ghi 
			var tk = _context.TbTaiKhoans.Where(p => p.IdNv == id).ToList();
			if (tk.Any())
			{
				// Nếu có bản ghi, xóa chúng trước
				_context.TbTaiKhoans.RemoveRange(tk);
			}

			_context.TbNhanViens.Remove(nv);
			_context.SaveChanges();
			return RedirectToAction(nameof(Index));
		}
		public IActionResult Create()
		{
			var mn = _context.TbNhanViens.OrderBy(m => m.IdNv).ToList();
			ViewBag.mn = mn;
			return View();
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Create(TbNhanVien mn)
		{
			if (ModelState.IsValid)
			{
				// Thêm dữ liệu mới vào bảng  trong cơ sở dữ liệu
				_context.TbNhanViens.Add(mn);
				_context.SaveChanges(); // Lưu thay đổi vào cơ sở dữ liệu

				return RedirectToAction("Index"); // Chuyển hướng đến trang Index sau khi thêm thành công
			}

			// Nếu ModelState không hợp lệ, trả về View với model để hiển thị lỗi
			return View(mn);
		}
        public IActionResult DanhSach()
        {
            var mn = _context.TbTaiKhoans.OrderBy(m => m.IdNguoiDung).ToList();
            return View(mn);
        }
		public IActionResult CreateTK()
		{
			var mn = _context.TbTaiKhoans.OrderBy(m => m.IdNguoiDung).ToList();
			ViewBag.mn = mn;
			return View();
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult CreateTK(TbTaiKhoan mn)
		{
			if (ModelState.IsValid)
			{
				var check = _context.TbTaiKhoans.Where(m => m.TenDangNhap == mn.TenDangNhap).FirstOrDefault();
				if (check != null)
				{
					Functions._MessageEmail = "Trùng tên đăng nhập";
					return RedirectToAction("DanhSach");
				}
				Functions._MessageEmail = string.Empty;
				mn.MatKhau = Functions.MD5Password(mn.MatKhau);
				// Thêm dữ liệu mới vào bảng  trong cơ sở dữ liệu
				_context.TbTaiKhoans.Add(mn);
				_context.SaveChanges(); // Lưu thay đổi vào cơ sở dữ liệu

				return RedirectToAction("Index"); // Chuyển hướng đến trang Index sau khi thêm thành công
			}

			// Nếu ModelState không hợp lệ, trả về View với model để hiển thị lỗi
			return View(mn);
		}

	}
}

DOAN/Views/NhanVien/Create.cshtml
@using DOAN.Utilities;
@model DOAN.Models.TbNhanVien;

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="page-wrapper">
    <div class="content container-fluid">
        <div class="page-header">
            <div class="row align-items-center">
                <div class="col">
                    <h3 class="page-title mt-5">Chỉnh sửa thông tin nhân viên </h3>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <form method="post">
                    <div class="row formtype">
                        <div class="col-md-4">
                            <div class="form-group">
                                <label asp-for="IdNv">ID</label>
                                <input type="text" class="form-control mb-3" asp-for="IdNv" placeholder="NV__">
                                <span asp-validation-for="IdNv" class="alert-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label asp-for="TenNv">Tên nhân viên</label>
                                <input type="text" class="form-control mb-3" asp-for="TenNv" placeholder="">
                                <span asp-validation-for="TenNv" class="alert-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label asp-for="NgaySinh">Ngày Sinh</label>
                                <div class="cal-icon">
                                    <input id="datetimepicker3" type="text" class="form-control datetimepicker" asp-for="NgaySinh" placeholder="mm/dd/yyyy">
                                </div>
                                <span asp-validation-for="NgaySinh" class="alert-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label asp-for="GioiTinh">Giới Tính</label>
                                <input type="text" class="form-control mb-3" asp-for="GioiTinh" placeholder="">
                                <span asp-validation-for="GioiTinh" class="alert-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label asp-for="DienThoai">Số Điện thoại</label>
                                <input type="text" class="form-control mb-3" asp-for="DienThoai" placeholder="">
                                <span asp-validation-for="DienThoai" class="alert-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label asp-for="DiaChi">Địa Chỉ</label>
                                <input type="text" class="form-control mb-3" asp-for="DiaChi" placeholder="">
                                <span asp-validation-for="DiaChi" class="alert-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label asp-for="IdCv">Chức vụ</label>
                                <select class="form-control" asp-for="IdCv">
                                    <option value="CV01">Quản Lý</option>
                                    <option value="CV02">Nhân Viên</option>
                                </select>
                                <span asp-validation-for="IdCv" class="alert-danger"></span>
                            </div>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary buttonedit">Lưu</button>
                    <a asp-controller="NhanVien" asp-action="Index" class="btn btn-lg btn-warning p-2">Quay lại</a>
                </form>
            </div>
        </div>
    </div>
</div>

<script>
    $(function () {
        $('#datetimepicker3').datetimepicker({
            format: 'LT'
        });
    });
</script>

DOAN/Views/NhanVien/CreateTK.cshtml
@using DOAN.Utilities;
@model DOAN.Models.TbTaiKhoan;

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="page-wrapper">
    <div class="content container-fluid">
        <div class="page-header">
            <div class="row align-items-center">
                <div class="col">
                    <h3 class="page-title mt-5">Chỉnh sửa tài khoản nhân viên</h3>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <form method="post">
                    <div class="row formtype">
                        <div class="col-md-4">
                            <div class="form-group">
                                <label asp-for="IdNguoiDung">ID</label>
                                <input type="text" class="form-control mb-3" asp-for="IdNguoiDung" placeholder="ND__">
                                <span asp-validation-for="IdNguoiDung" class="alert-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label asp-for="IdNv">ID nhân viên</label>
                                <input type="text" class="form-control mb-3" asp-for="IdNv" placeholder="NV__">
                                <span asp-validation-for="IdNv" class="alert-danger"></span>
                            </div>
                        </div>
                        
                        <div class="col-md-4">
                            <div class="form-group">
                                <label asp-for="TenDangNhap">Tên đăng nhập </label>
                                <input type="text" class="form-control mb-3" asp-for="TenDangNhap">
                                <span asp-validation-for="TenDangNhap" class="alert-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label asp-for="MatKhau">Mật khẩu</label>
                                <input type="password" class="form-control mb-3" asp-for="MatKhau">
                                <span asp-validation-for="MatKhau" class="alert-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label asp-for="TrangThai">Trạng thái</label>
                                <input type="text" class="form-control mb-3" asp-for="TrangThai">
                                <span asp-validation-for="TrangThai" class="alert-danger"></span>
                            </div>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary buttonedit">Lưu</button>
                    <a asp-controller="NhanVien" asp-action="DanhSach" class="btn btn-lg btn-warning p-2">Quay lại</a>
                </form>
            </div>
        </div>
    </div>
</div>

DOAN/Views/NhanVien/DanhSach.cshtml
@using DOAN.Models;
@model IList<TbTaiKhoan>

<div class="page-wrapper">
	<div class="content container-fluid">
		<div class="page-header">
			<div class="row align-items-center">
				<div class="col">
					<div class="mt-5">
						<div class="top-nav-search">
							<form>
								<input type="text" class="form-control" placeholder="Tìm Kiếm">
								<button class="btn" type="submit"><i class="fas fa-search"></i></button>
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-sm-12">
				<div class="card card-table">
					<div class="card-body booking_card">
						<div class="table-responsive">
							<table class="datatable table table-stripped table table-hover table-center mb-0">
								<thead>
									<tr>
										<th>ID</th>
										<th>ID nhân viên</th>
										<th>Tên đăng nhập</th>
										<th>Mật khẩu</th>
										<th>Trạng thái</th>
										<th>Hành động</th>
									</tr>
								</thead>
								<tbody>
									@foreach (var kh in Model)
									{
										<tr>
											<td>@kh.IdNguoiDung</td>
											<td>@kh.IdNv</td>
											<td>@kh.TenDangNhap</td>
											<td>@kh.MatKhau</td>
											<td>
												@if (kh.TrangThai==true)
												{
													<span>Hoạt động</span>
												}
												else
												{
													<span>Không hoạt động</span>
												}
											</td>
											<td class="text-right">
												<div class="dropdown dropdown-action">
													<a href="#" class="action-icon dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><i class="fas fa-ellipsis-v ellipse_color"></i></a>
													<div class="dropdown-menu dropdown-menu-right">
														<a class="dropdown-item" asp-action="Edit" asp-route-id="@kh.IdNguoiDung"><i class="fas fa-pencil-alt m-r-5"></i>Sửa</a>


														<a class="dropdown-item delete-action" data-toggle="modal" data-target="#deleteModal-@kh.IdNguoiDung"><i class="fas fa-trash-alt m-r-5"></i> Xóa</a>
													</div>
												</div>
											</td>
										</tr>
									}

								</tbody>
							</table>
						</div>
					</div>
				</div>
			</div>
		</div>
		@foreach (var kh in Model)
		{
			<div class="modal fade delete-modal" id="deleteModal-@kh.IdNguoiDung" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
				<div class="modal-dialog modal-dialog-centered">
					<div class="modal-content">
						<div class="modal-body text-center">
							<img src="~/assets/img/sent.png" alt="" width="50" height="46">
							<h3 class="delete_class">Bạn chắc chắn muốn xóa không?</h3>
							<div class="m-t-20">
								<a href="#" class="btn btn-white" data-dismiss="modal">Close</a>
								<form asp-action="Delete" asp-route-id="@kh.IdNguoiDung">
									<button type="submit" class="btn btn-danger">Xóa</button>
								</form>

							</div>
						</div>
					</div>
				</div>
			</div>
		}
	</div>
</div>

DOAN/Views/NhanVien/Index.cshtml
@using DOAN.Models;
@model IList<TbNhanVien>

<div class="page-wrapper">
	<div class="content container-fluid">
		<div class="page-header">
			<div class="row align-items-center">
				<div class="col">
					<div class="mt-5">
						<div class="top-nav-search">
							<form>
								<input type="text" class="form-control" placeholder="Tìm Kiếm">
								<button class="btn" type="submit"><i class="fas fa-search"></i></button>
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-sm-12">
				<div class="card card-table">
					<div class="card-body booking_card">
						<div class="table-responsive">
							<table class="datatable table table-stripped table table-hover table-center mb-0">
								<thead>
									<tr>
										<th>ID</th>
										<th>Họ Tên</th>
										<th>Ngày sinh</th>
										<th>Giới tính</th>
										<th>Điện thoại</th>
										<th>Địa chỉ</th>
										<th>Chức vụ</th>
										<th>Hành động</th>
									</tr>
								</thead>
								<tbody>
									@foreach (var kh in Model)
									{
										<tr>
											<td>@kh.IdNv</td>
											<td>@kh.TenNv</td>
											<td>@((kh.NgaySinh != null) ? ((DateTime)kh.NgaySinh).ToString("dd/MM/yyyy") : "")</td>
											<td>@kh.GioiTinh</td>
											<td>@kh.DienThoai</td>
											<td>@kh.DiaChi</td>
											<td>
												@{
													string chucVu = kh.IdCv switch
													{
														"CV01" => "Quản lý",
														"CV02" => "Nhân viên",
														
													};
													@chucVu
												}
											</td>
											<td class="text-right">
												<div class="dropdown dropdown-action">
													<a href="#" class="action-icon dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><i class="fas fa-ellipsis-v ellipse_color"></i></a>
													<div class="dropdown-menu dropdown-menu-right">
														<a class="dropdown-item" asp-action="Edit" asp-route-id="@kh.IdNv"><i class="fas fa-pencil-alt m-r-5"></i>Sửa</a>


														<a class="dropdown-item delete-action" data-toggle="modal" data-target="#deleteModal-@kh.IdNv"><i class="fas fa-trash-alt m-r-5"></i> Xóa</a>
													</div>
												</div>
											</td>
										</tr>
									}

								</tbody>
							</table>
						</div>
					</div>
				</div>
			</div>
		</div>
		@foreach (var kh in Model)
		{
			<div class="modal fade delete-modal" id="deleteModal-@kh.IdNv" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
				<div class="modal-dialog modal-dialog-centered">
					<div class="modal-content">
						<div class="modal-body text-center">
							<img src="~/assets/img/sent.png" alt="" width="50" height="46">
							<h3 class="delete_class">Bạn chắc chắn muốn xóa không?</h3>
							<div class="m-t-20">
								<a href="#" class="btn btn-white" data-dismiss="modal">Close</a>
								<form asp-action="Delete" asp-route-id="@kh.IdNv">
									<button type="submit" class="btn btn-danger">Xóa</button>
								</form>

							</div>
						</div>
					</div>
				</div>
			</div>
		}
	</div>
</div>