DOAN/Controllers/DangNhapController.cs
using DOAN.Utilities;
using DOAN.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace DOAN.Controllers
{
    public class DangNhapController : Controller
    {
        private readonly QlksContext _context;
        public DangNhapController(QlksContext context)
        {
            _context = context;
        }

        // Phương thức Index hiển thị trang đăng nhập
        public IActionResult Index()
        {
            return View();
        }

        // Phương thức xử lý đăng nhập
        [HttpPost]
        public IActionResult Index(TbTaiKhoan user)
        {
            if (user == null)
            {
                Functions._Message = "Dữ liệu người dùng bị thiếu.";
                return View(user);
            }
            var mn = _context.TbTaiKhoans.FirstOrDefault();
            // Kiểm tra trạng thái của tài khoản
            if ( mn.TrangThai == false)
            {
                Functions._Message = "Tài khoản không hoạt động!";
                return View(user);
            }
            string pw = Functions.MD5Password(user.MatKhau);
            var check = _context.TbTaiKhoans.FirstOrDefault(m => m.TenDangNhap == user.TenDangNhap && m.MatKhau == pw);

            if (check == null)
            {
                Functions._Message = "Sai username hoặc password!";
                return View(user);
            }
            
            Functions._Message = string.Empty;
            Functions._AccountId = check.IdNguoiDung.ToString();
            Functions._Username = string.IsNullOrEmpty(check.TenDangNhap) ? string.Empty : check.TenDangNhap;
            return RedirectToAction("Index", "Home");
        }
        

    }
}

DOAN/Views/DangNhap/Index.cshtml
@using DOAN.Utilities;
@model DOAN.Models.TbTaiKhoan
@{
    Layout = "";
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0">
    <title>Hotel Dashboard Template</title>
    <link rel="shortcut icon" type="image/x-icon" href="~/assets/img/favicon.png">
    <link rel="stylesheet" href="~/assets/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/assets/plugins/fontawesome/css/fontawesome.min.css">
    <link rel="stylesheet" type="text/css" href="~/assets/plugins/fontawesome/css/all.min.css">
    <link rel="stylesheet" href="~/assets/css/feathericon.min.css">
    <link rel="stylesheet" href="~/assets/plugins/morris/morris.css">
    <link rel="stylesheet" href="~/assets/css/style.css">
</head>
<body>
    <div class="main-wrapper login-body">
        <div class="login-wrapper">
            <div class="container">
                <div class="loginbox">
                    <div class="login-left">
                        
                        <img class="img-fluid" src="~/assets/img/123.png" alt="Logo">
                    </div>
                    <div class="login-right">
                        <div class="login-right-wrap">
                            <h1>Login</h1>
                            <p class="account-subtitle"></p>
                            <form asp-controller="DangNhap" asp-action="Index" method="post">
                                <div class="form-group">
                                    <input asp-for="TenDangNhap" class="form-control" type="text" placeholder="Tên Đăng Nhập" autocomplete="off">
                                </div>
                                <div class="form-group">
                                    <input asp-for="MatKhau" class="form-control" type="password" placeholder="Mật khẩu" autocomplete="off">
                                </div>
                                <div class="col-12 text-danger">
                                    @Functions._Message
                                </div>
                                <div class="form-group">
                                    <button class="btn btn-primary btn-block" type="submit">Login</button>
                                </div>
                            </form>
                            <div class="text-center forgotpass">
                                <a href="forgot-password.html">
                                    Quên mật khẩu?
                                </a>
                            </div>
                            <div class="login-or"><span class="or-line"></span><span class="span-or">or</span></div>
                            <div class="social-login"><span>Login with</span> <a href="#" class="facebook"><i class="fab fa-facebook-f"></i></a><a href="#" class="google"><i class="fab fa-google"></i></a></div>
                            <div class="text-center dont-have">Don’t have an account? <a href="register.html">Register</a></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="~/assets/js/jquery-3.5.1.min.js"></script>
    <script src="~/assets/js/popper.min.js"></script>
    <script src="~/assets/js/bootstrap.min.js"></script>
    <script src="~/assets/plugins/slimscroll/jquery.slimscroll.min.js"></script>
    <script src="~/assets/js/script.js"></script>
</body>
</html>